=== baebigroot/bandwiki/XML/musical_band.dtd
<!-- NGUYEN Kieu Nhung - RAFIDISON Lovanomena-->


													<!--ENTITY-->
<!ENTITY % monthval "(1|2|3|4|5|6|7|8|9|10|11|12)">
<!ENTITY % dayval
	 "(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31)"> 
<!ENTITY % year "CDATA"> 
<!ENTITY % inline "img | a">
<!ENTITY % datainline "(#PCDATA | %inline;)*">
<!ENTITY % datainlineul "(#PCDATA | p | %inline; | ul)*">
<!ENTITY % coreattrs
	 "id       ID      #IMPLIED
	  class    CDATA   #IMPLIED
	  title    CDATA   #IMPLIED">

<!ENTITY % URI "CDATA">
<!-- a Uniform Resource Identifier, see [RFC2396] -->

<!ENTITY % Length "CDATA">
<!-- nn for pixels or nn% for percentage length -->

<!ENTITY % Text "CDATA">
<!-- used for titles etc. -->

<!ELEMENT img EMPTY>
<!ATTLIST img
	%coreattrs;
	src         %URI; #REQUIRED
	alt         %Text; #REQUIRED
	longdesc    %URI;          #IMPLIED
	height      %Length;       #IMPLIED
	width       %Length;       #IMPLIED
	>

<!ELEMENT a (#PCDATA)*>
<!ATTLIST a
	%coreattrs;
  	href        %URI;          #IMPLIED
>

<!ELEMENT p %datainline;>
<!ATTLIST p 
	%coreattrs;>

<!ELEMENT ul (li)+>
<!ELEMENT li %datainlineul;>
<!ATTLIST li
	%coreattrs;
	begin %year; #IMPLIED
	end   %year; #IMPLIED
	year  %year; #IMPLIED
	>
													<!--GENERAL STRUCTURE-->
<!ELEMENT musical_band (cover, introduction, discography)>
<!ATTLIST musical_band
	%coreattrs;
    author    	CDATA	#IMPLIED
	year		%year;	#REQUIRED>

													<!--COVER-->
<!ELEMENT cover (group_name, group_photo)>
<!ATTLIST cover
	%coreattrs;>
<!ELEMENT group_name %datainline;>
<!ATTLIST group_name
	%coreattrs;>
<!ELEMENT group_photo (img+)>
<!ATTLIST group_photo
	%coreattrs;>	

													<!--INTRODUCTION-->
<!ELEMENT introduction (overview, logo?, group_data, current_members)>
<!ATTLIST introduction
	%coreattrs;>

<!ELEMENT overview %datainlineul;>
<!ATTLIST overview
	%coreattrs;>

<!ELEMENT logo (img+)>
<!ATTLIST logo
	%coreattrs;>
	
<!ELEMENT group_data (country,activeyear,musicalgenres,instruments,labels)>
<!ATTLIST group_data
	%coreattrs;>
<!ELEMENT country %datainline;>	
<!ATTLIST country
	%coreattrs;>
<!ELEMENT activeyear %datainline;>	
<!ATTLIST activeyear
	%coreattrs;>
<!ELEMENT musicalgenres %datainline;>
<!ATTLIST musicalgenres
	%coreattrs;>
<!ELEMENT instruments %datainline;>
<!ATTLIST instruments 
    %coreattrs;>
<!ELEMENT labels %datainline;>
<!ATTLIST labels 
    %coreattrs;>  
	
<!ELEMENT current_members (member+)>
<!ATTLIST current_members
    %coreattrs;>
<!ELEMENT member (member_photo,name,birthday,positions)>
<!ATTLIST member
	%coreattrs;>
<!ELEMENT member_photo (img+)>
<!ATTLIST member_photo
	%coreattrs;>
<!ELEMENT name %datainline;>
<!ATTLIST name
    %coreattrs;> 	
<!ELEMENT birthday EMPTY>
<!ATTLIST birthday 
    %coreattrs;
    year     %year;       #REQUIRED
	month    %monthval;   #IMPLIED
	day      %dayval;     #IMPLIED
	>
<!ELEMENT positions %datainline;>
<!ATTLIST positions
    %coreattrs;>

	  

													<!--DISCOGRAPHY-->
	
<!ELEMENT discography (albums+,singles+)>
<!ATTLIST discography
    %coreattrs;>		
<!ELEMENT albums (album_name+)>
<!ATTLIST albums
	%coreattrs;>	  
<!ELEMENT album_name %datainline;>
<!ATTLIST album_name
	%coreattrs;>	  
<!ELEMENT singles (single_name+)>
<!ATTLIST singles
	%coreattrs;>	  
<!ELEMENT single_name %datainline;>
<!ATTLIST single_name
	%coreattrs;>

=== baebigroot/bandwiki/XML/Arctic-Monkeys.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE musical_band SYSTEM "musical_band.dtd">

<musical_band author="NGUYEN Nhung" year="2022">
    <cover>
        <group_name> Arctic Monkeys </group_name>
        <group_photo>
            <img src="../Images/AM/cover.jpg" alt="Arctic Monkeys"/>
        </group_photo>
    </cover>

    <introduction>
        <overview>
            <p>
                Arctic Monkeys are an English rock band formed in Sheffield in 2002. They were heralded as one of the first bands to come to public attention via the Internet, with commentators suggesting they represented the possibility of a change in the way in which new bands are promoted and marketed. Their debut album, "Whatever People Say I Am, That's What I'm Not" (2006), became the fastest-selling debut album in UK chart history, and has been hailed as one of the greatest debut albums.
            </p>
        </overview>
        <group_data>
            <country> Country: England </country>
            <activeyear> Active year: 2002-present </activeyear>
            <musicalgenres>  Musical genres: Indie rock, garage rock, post-punk revival, psychedelic rock, alternative rock, post-Britpop </musicalgenres>
            <instruments> Instrument(s) : Voice, Guitar, Bass, Keyboards, Drums </instruments>
            <labels> Labels : Domino </labels>
        </group_data>
        <current_members>
            <member>
                <member_photo>
                    <img src="../Images/AM/Alex_Turner.jpg" alt="Alex Turner" />
                </member_photo>
                <name> Name: Alex Turner</name>
                <birthday year="1986" month="1" day="6"/>
                <positions> Positions: lead vocals, guitar, keyboards </positions>
            </member>
            <member>
                <member_photo>
                    <img src="../Images/AM/Jamie_Cook.jpg" alt="Jamie Cook" />
                </member_photo>
                <name> Name: Jamie Cook </name>
                <birthday year="1985" month="7" day="8"/>
                <positions> Positions: guitar, keyboards </positions>
            </member>
            <member>
                <member_photo>
                    <img src="../Images/AM/Matt.jpg" alt="Matt Helders" />
                </member_photo>
                <name> Name: Matt Helders </name>
                <birthday year="1986" month="5" day="7"/>
                <positions> Positions: drums, backing vocals </positions>
            </member>
            <member>
                <member_photo>
                    <img src="../Images/AM/Nick_OMalley.jpg" alt="Nick O'Malley" />
                </member_photo>
                <name> Name: Nick O'Malley </name>
                <birthday year="1985" month="7" day="5"/>
                <positions> Positions: bass guitar, backing vocals </positions>
            </member>
        </current_members>
    </introduction>
    
    <discography>
        <albums>
            <album_name>
                Whatever People Say I Am, That's What I'm Not
                <img src="../Images/AM/whatever.jpg" alt="Whatever People Say I Am, That's What I'm Not"/>
            </album_name>    
            <album_name>
                Favourite Worst Nightmare
                <img src="../Images/AM/favourite.jpg" alt="Favourite Worst Nightmare"/>
            </album_name>
            <album_name>
                Humbug 
                <img src="../Images/AM/humbug.jpg" alt="Humbug"/>
            </album_name>
            <album_name>
                Suck It and See
                <img src="../Images/AM/suck.jpg" alt="Suck It and See"/>
            </album_name>
            <album_name>
                AM
                <img src="../Images/AM/am.jpg" alt="AM"/>
            </album_name>
            <album_name>
                Tranquility Base Hotel and Casino 
                <img src="../Images/AM/tranquility.jpg" alt="Tranquility Base Hotel and Casino "/>
            </album_name>                
        </albums>
        <singles>        
            <single_name>
                505
                <img src="../Images/AM/505.jpg" alt="505"/>
            </single_name>           
            <single_name>
                Do I Wanna Know
                <img src="../Images/AM/do-i-wanna-know.jpg" alt="Do I Wanna Know"/>
            </single_name>            
            <single_name>
                Knee Socks
                <img src="../Images/AM/knee-socks.jpg" alt="Knee Socks"/>
            </single_name>
            <single_name>
                Fluorescent Adolescent
                <img src="../Images/AM/fluorescent.jpg" alt="Fluorescent Adolescent"/>
            </single_name>                    
        </singles>
    </discography>
</musical_band>

=== baebigroot/bandwiki/XML/Imagine-Dragons.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE musical_band SYSTEM "musical_band.dtd">

<musical_band author="NGUYEN Nhung" year="2022">
    <cover>
        <group_name> Imagine Dragons </group_name>
        <group_photo>
            <img src="../Images/ID/cover2.jpg" alt="Imagine Dragons"/>
        </group_photo>
    </cover>

    <introduction>
        <overview>
            <p>
                Imagine Dragons is an American pop rock band from Las Vegas, Nevada. Formed in 2009, Imagine Dragons first revealed their 
                limitless passion and genre-bending sensibilities with a series of independently 
                released EPs that quickly earned a grassroots following
            </p>
            <p>            
                Over the last half-decade, Imagine Dragons have emerged as one of the biggest and most compelling rock bands in the world. 
            </p>
        </overview>
        <group_data>
            <country> Country: USA </country>
            <activeyear> Active year: 2008-present </activeyear>
            <musicalgenres>  Musical genres: Pop rock, electropop, pop, indie pop, arena rock, alternative rock </musicalgenres>
            <instruments> Instrument(s) : Voice, Guitar, Bass, Drum </instruments>
            <labels> Labels : Kidinakorner, Interscope </labels>
        </group_data>
        <current_members>
            <member>
                <member_photo>
                    <img src="../Images/ID/Dan_Reynolds.jpg" alt="Dan Reynolds" />
                </member_photo>
                <name> Name: Dan Reynolds </name>
                <birthday year="1987" month="7" day="14"/>
                <positions> Positions: lead vocals, guitars, piano, keyboards, bass, drums, percussion </positions>
            </member>
            <member>
                <member_photo>
                    <img src="../Images/ID/Sermon.jpg" alt="Wayne Sermon"/>
                </member_photo>
                <name> Name: Wayne Sermon </name>
                <birthday year="1984" month="6" day="15"/>
                <positions> Positions: guitars, backing vocals, mandolin, drums, percussion, piano, synthesizers</positions>
            </member>
            <member>
                <member_photo>
                    <img src="../Images/ID/Ben_McKee.jpg" alt="Ben McKee" />
                </member_photo>
                <name> Name: Ben Mckee </name>
                <birthday year="1985" month="4" day="7"/>
                <positions> Positions: bass, piano, keyboards, synthesizers, backing vocals, guitars, drums, percussion</positions>
            </member>
            <member>
                <member_photo>
                    <img src="../Images/ID/Daniel_Platzman.jpg" alt="Daniel Platzman" />
                </member_photo>
                <name> Name: Daniel Platzman </name>
                <birthday year="1986" month="9" day="28"/>
                <positions> Positions: drums, percussion, backing vocals, guitars, viola, keyboards </positions>
            </member>
        </current_members>
    </introduction>
    
    <discography>
        <albums>
            <album_name>
                Night Visions
                <img src="../Images/ID/night-visions.jpg" alt="Night Visions"/>
            </album_name>    
            <album_name>
                Smoke + Mirrors
                <img src="../Images/ID/smoke+mirrors.png" alt="Smoke + Mirrors"/>
            </album_name>
            <album_name>
                Evolve
                <img src="../Images/ID/evolve.jpg" alt="Evolve"/>
            </album_name>
            <album_name>
                Origins
                <img src="../Images/ID/origins.jpg" alt="Origins"/>
            </album_name>
            <album_name>
                Mercury - Act 1
                <img src="../Images/ID/mercury.jpg" alt="Mercury - Act 1"/>
            </album_name>
        </albums>
        <singles>        
            <single_name>
                Shots
                <img src="../Images/ID/shots.jpg" alt="Shots"/>
            </single_name>           
            <single_name>
                Thunder
                <img src="../Images/ID/thunder.jpg" alt="Thunder"/>
            </single_name>            
            <single_name>
                Next to me
                <img src="../Images/ID/next-to-me.jpg" alt="Next to me"/>
            </single_name>
            <single_name>
                Enemy
                <img src="../Images/ID/enemy.jpg" alt="Enemy"/>
            </single_name>                    
        </singles>
    </discography>
</musical_band>

=== baebigroot/bandwiki/XML/Tomorrow-X-Together.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE musical_band SYSTEM "musical_band.dtd">

<musical_band author="Rafidison Lovanomena" year="2022">
    <cover>
        <group_name> Tomorrow X Together </group_name>
        <group_photo>
			<img  src="../Images/TXT/txt-cov1.jpg" alt="TXT" />
        </group_photo>
    </cover>

    <introduction>
        <overview>
            <p>
                ONE DREAM! Hello, We are TOMORROW X TOGETHER!" â€” TXT's Introduction 
            </p>
            <p>
                TOMORROW X TOGETHER (read as Tomorrow by Together; commonly known as TXT)is a five-member boy group under Big Hit Music (formerly Big Hit Entertainment). The members don't have any official fixed positions, except for the leader. They debuted on March 4, 2019, with their first mini album The Dream Chapter: STAR at Mnet's 'Debut Celebration Show'. According to their website, the meaning behind "Tomorrow by Together" is five individuals who "come together under one dream in hopes of building a better tomorrow".
            </p>
        </overview>
        <logo>
			<img src="../Images/TXT/txt-logo.jpeg"  alt="Logo TXT"/>
        </logo>
        <group_data>
            <country> Country: South Korea </country>
            <activeyear> Active year: 2019-present </activeyear>
            <musicalgenres>  Musical genres: K-pop, J-pop </musicalgenres>
            <instruments> Instrument(s): Voice </instruments>
            <labels> Labels: Big Hit Music, Hybe Corporation, Republic Records </labels>
        </group_data>
        <current_members>
            <member>
                <member_photo>
					<img src="../Images/TXT/Yeonjun.jpg" alt="Yeonjun" />
                </member_photo>
                 <name> Yeonjun </name>
                <birthday year="1999" month="9" day="13"/>
                <positions> Rapper, Dancer, Vocalist </positions>
            </member>
            <member>
                <member_photo>
                    <img src="../Images/TXT/Soobin.jpg" alt="Soobin" />
                </member_photo>
                <name> Soobin </name>
                <birthday year="2000" month="12" day="5"/>
                <positions> Leader, Vocalist, Rapper, Dancer </positions>
            </member>
            <member>
                <member_photo>
                    <img src="../Images/TXT/Beomgyu.jpg" alt="Beomgyu"/>
                </member_photo>
                <name> Beomgyu </name>
                <birthday year="2001" month="3" day="13"/>
                <positions> Vocalist, Dancer, Rapper, Center, Visual </positions>
            </member>
            <member>
                <member_photo>
                    <img src="../Images/TXT/Taehyun.jpg" alt="Taehyun"/>
                </member_photo>
                <name> Taehyun </name>
                <birthday year="2002" month="2" day="5"/>
                <positions> Vocalist, Rapper, Dancer </positions>
            </member>
            <member>
                <member_photo>
                    <img src="../Images/TXT/Hueningkai.jpg" alt="Hueningkai"/>
                </member_photo>
                <name> Hueningkai </name>
                <birthday year="2002" month="8" day="14"/>
                <positions> Maknae, Vocalist, Rapper, Dancer, Visual </positions>
            </member>
        </current_members>
    </introduction>
    
    <discography>
        <albums>
            <album_name>
                Minisode 2: Thursday's Child
                <img src="../Images/TXT/Minisode2-Thursday's_Child.jpg" alt="The Chaos Chapter-FIGHT OR ESCAPE"/>
            </album_name>
            <album_name>
                The Chaos Chapter: FIGHT OR ESCAPE
                <img src="../Images/TXT/The_Chaos_Chapter-FIGHT_OR_ESCAPE.jpg" alt="The Chaos Chapter-FIGHT OR ESCAPE"/>
            </album_name>    
            <album_name>
                The Chaos Chapter: FREEZE
                <img src="../Images/TXT/The_Chaos_Chapter-FREEZE.jpg" alt="The Chaos Chapter-FREEZE"/>
            </album_name>
            <album_name>
                Minisode1 : Blue Hour
                <img src="../Images/TXT/Minisode1-Blue_Hour.jpg" alt="Minisode 1-Blue Hour"/>
            </album_name>
            <album_name>
                The Dream Chapter: ETERNITY
                <img src="../Images/TXT/The_Dream_Chapter-ETERNITY.jpg" alt="The Dream Chapter-ETERNITY"/>
            </album_name>
            <album_name>
                The Dream Chapter: MAGIC
                <img src="../Images/TXT/The_Dream_Chapter-MAGIC.jpg" alt="The Dream Chapter-MAGIC"/>
            </album_name>
            <album_name>
                The Dream Chapter: STAR
                <img src="../Images/TXT/The_Dream_Chapter-STAR.jpg" alt="he Dream Chapter-STAR"/>
            </album_name>
        </albums>
        <singles>
            <single_name>
                0X1=LOVESONG (I Know I Love You)feat.MOD SUN
                <img src="../Images/TXT/0X1=LOVESONG.jpg" alt="0X1=LOVESONG (I Know I Love You)"/>
                Drama(Japanese Ver.)
                <img src="../Images/TXT/Drama.jpg" alt="Drama"/>
            </single_name>            
            <single_name>
                MAGIC HOUR
                <img src="../Images/TXT/Magic_Hour.jpg" alt="Magic Hour"/>
            </single_name>           
            <single_name>
                Our Summer(Acoustic Mix)
                <img src="../Images/TXT/Our_Summer.jpg" alt="Our Summer"/>
            </single_name>
            <single_name>
                Cat &amp; Dog (Eng Ver.)
                <img src="../Images/TXT/Cat_Dog.jpg" alt="Cat &amp; Dog"/>
            </single_name>
        </singles>
    </discography>
</musical_band>

=== baebigroot/bandwiki/XML/Stray-Kids.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE musical_band SYSTEM "musical_band.dtd">

<musical_band author="Rafidison Lovanomena" year="2022">
    <cover>
        <group_name> Stray Kids </group_name>
        <group_photo>
            <img  src="../Images/SKZ/skz-cov1.jpg" alt="Stray Kids" />
        </group_photo>
    </cover>

    <introduction>
        <overview>
            <p>
                "Step Out! Hello, We are Stray Kids" â€• Stray Kids' introduction
            </p>
            <p>
                Stray Kids is an eight-member boy group under JYP Entertainment.
                Formed through the competition reality show of the same name and debuted on March 25, 2018,
                with the mini album I Am Not.
                The name of the group is named by the team members. The group name expresses their determination
                to break the existing mold and go one step forward to be out of the ordinary.
            </p>
        </overview>
        <logo>
            <img src="../Images/SKZ/skz_logo.jpg" alt="SKZ Logo" height="260"/>
        </logo>
        <group_data>
            <country> Country: South Korea </country>
            <activeyear> Active year: 2018-present </activeyear>
            <musicalgenres>  Musical genres: K-pop,K-hip-hop,K-rap,J-pop </musicalgenres>
            <instruments> Instrument(s) : Voice </instruments>
            <labels> Labels : JYP Entertainment, Sony Music Entertainment Japan </labels>
        </group_data>
        <current_members>
            <member>
                <member_photo>
                    <img src="../Images/SKZ/Bang_Chan.jpg" alt="Bang Chan" />
                </member_photo>
                <name> Bang Chan </name>
                <birthday year="1997" month="10" day="3"/>
                <positions> Leader, Lead Vocalist, Lead Dancer, Sub-Rapper, Producer </positions>
            </member>
            <member>
                <member_photo>
                    <img  src="../Images/SKZ/Lee_Know.jpeg" alt="Lee Know" />
                </member_photo>
                <name> Lee Know </name>
                <birthday year="1998" month="10" day="25"/>
                <positions> Main Dancer, Vocalist, Sub-Rapper </positions>
            </member>
            <member>
                <member_photo>
                    <img  src="../Images/SKZ/Changbin.jpeg" alt="Changbin" />
                </member_photo>
                <name> Changbin </name>
                <birthday year="1999" month="8" day="11"/>
                <positions> Main Rapper, Sub-Vocalist, Producer </positions>
            </member>
            <member>
                <member_photo>
                    <img  src="../Images/SKZ/Hyunjin.jpg" alt="Hyunjin" />
                </member_photo>
                <name> Hyunjin </name>
                <birthday year="2000" month="3" day="20"/>
                <positions> Main Dancer, Lead Rapper, Sub-Vocalist, Visual </positions>
            </member>
            <member>
                <member_photo>
                    <img  src="../Images/SKZ/Han.jpeg" alt="Han" />
                </member_photo>
                <name> Han </name>
                <birthday year="2000" month="9" day="14"/>
                <positions> Main Rapper, Lead Vocalist, Producer </positions>
            </member>
            <member>
                <member_photo>
                    <img  src="../Images/SKZ/Felix.jpg" alt="Felix" />
                </member_photo>
                <name> Felix </name>
                <birthday year="2000" month="9" day="15"/>
                <positions> Lead Dancer, Lead Rapper, Sub-Vocalist </positions>
            </member>
            <member>
                <member_photo>
                    <img  src="../Images/SKZ/Seungmin.jpg" alt="Seungmin" />
                </member_photo>
                <name> Seungmin </name>
                <birthday year="2000" month="9" day="22"/>
                <positions> Main Vocalist </positions>
            </member>
            <member>
                <member_photo>
                    <img src="../Images/SKZ/I.N.jpg" alt="I.N" />
                </member_photo>
                <name> I.N </name>
                <birthday year="2001" month="2" day="8"/>
                <positions> Vocalist, Maknae </positions>
            </member>
        </current_members>
    </introduction>
    
    <discography>
        <albums>
            <album_name>
                ODDINARY
                <img src="../Images/SKZ/ODDINARY.jpg" alt="ODDINARY"/>
            </album_name>
            <album_name>
                SKZ2021
                <img src="../Images/SKZ/SKZ2021.jpg" alt="SKZ2021"/>
            </album_name>    
            <album_name>
                Christmas EveL
                <img src="../Images/SKZ/Christmas_EveL.jpg" alt="Christmas EveL"/>
            </album_name>  
            <album_name>
                NOEASY
                <img src="../Images/SKZ/NOEASY.jpg" alt="NOEASY"/>
            </album_name>
            <album_name>
                ALL IN
                <img src="../Images/SKZ/All_In.jpg" alt="ALL IN"/>
            </album_name>
            <album_name>
                IN LIFE
                <img src="../Images/SKZ/IN_Life.jpg" alt="IN LIFE"/>
            </album_name>
            <album_name>
                GO LIVE
                <img src="../Images/SKZ/Go_Live.jpg" alt="GO LIVE"/>
            </album_name>
            <album_name>
                Cle:Levanter
                <img src="../Images/SKZ/Cle_Levanter.jpg" alt="Cle:Levanter"/>
            </album_name>
            <album_name>
                Cle 2:Yellow Wood
                <img src="../Images/SKZ/Cle_2_yellow_wood.jpg" alt="Cle 2:Yellow Wood"/>
            </album_name>
            <album_name>
                Cle 1:Miroh
                <img src="../Images/SKZ/Cle_1_MIROH.jpg" alt="Cle 1:Miroh"/>
            </album_name>
            <album_name>
                I Am You
                <img src="../Images/SKZ/I_Am_You.jpg" alt="I Am You"/>
            </album_name>
            <album_name>
                I Am Who
                <img src="../Images/SKZ/I_am_Who.jpg" alt="I Am Who"/>
            </album_name>
            <album_name>
                I Am Not
                <img src="../Images/SKZ/I_Am_Not.jpg" alt="I Am Not"/>
            </album_name>
            <album_name>
                Mixtape
                <img src="../Images/SKZ/Mixtape.jpg" alt="Mixtape"/>
            </album_name>
        </albums>
        <singles>
            <single_name> 
                Mixtape:Oh 
                <img src="../Images/SKZ/Mixtape_oh.jpg" alt="Mixtape:Oh"/>
            </single_name>
            <single_name> 
                TOP 
                <img src="../Images/SKZ/TOP.jpg" alt="TOP"/>
            </single_name>   
            <single_name> 
                Mixtape:On Track 
                <img src="../Images/SKZ/Mixtape_On_Track.jpg" alt="Mixtape:On Track"/>
            </single_name>
            <single_name> 
                Mixtape:Gone Days 
                <img src="../Images/SKZ/Mixtape_Gone_Days.jpg" alt="Mixtape:Gone Days"/>
            </single_name>
            <single_name> 
                Double Knot 
                <img src="../Images/SKZ/Double_Knot.jpg" alt="Double Knot"/>
            </single_name>
            <single_name> 
                Hellevator 
                <img src="../Images/SKZ/Hellevator.jpg" alt="Hellevator"/>
            </single_name>
        </singles>
    </discography>
</musical_band>
